config/routes.rb
# == Route Map
root 'welcome#index'
#
#                   Prefix Verb   URI Pattern                          Controller#Action
#         new_user_session GET    /users/sign_in(.:format)             devise/sessions#new
#             user_session POST   /users/sign_in(.:format)             devise/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)            devise/sessions#destroy
#            user_password POST   /users/password(.:format)            devise/passwords#create
#        new_user_password GET    /users/password/new(.:format)        devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format)       devise/passwords#edit
#                          PATCH  /users/password(.:format)            devise/passwords#update
#                          PUT    /users/password(.:format)            devise/passwords#update
# cancel_user_registration GET    /users/cancel(.:format)              devise/registrations#cancel
#        user_registration POST   /users(.:format)                     devise/registrations#create
#    new_user_registration GET    /users/sign_up(.:format)             devise/registrations#new
#   edit_user_registration GET    /users/edit(.:format)                devise/registrations#edit
#                          PATCH  /users(.:format)                     devise/registrations#update
#                          PUT    /users(.:format)                     devise/registrations#update
#                          DELETE /users(.:format)                     devise/registrations#destroy
#     unauthenticated_root GET    /                                    home#index
#      customer_home_index GET    /customer/home(.:format)             customer/home#index
#         admin_home_index GET    /admin/home(.:format)                admin/home#index
#          admin_customers GET    /admin/customers(.:format)           admin/customers#index
#                          POST   /admin/customers(.:format)           admin/customers#create
#       new_admin_customer GET    /admin/customers/new(.:format)       admin/customers#new
#      edit_admin_customer GET    /admin/customers/:id/edit(.:format)  admin/customers#edit
#           admin_customer GET    /admin/customers/:id(.:format)       admin/customers#show
#                          PATCH  /admin/customers/:id(.:format)       admin/customers#update
#                          PUT    /admin/customers/:id(.:format)       admin/customers#update
#                          DELETE /admin/customers/:id(.:format)       admin/customers#destroy
#         admin_categories GET    /admin/categories(.:format)          admin/categories#index
#                          POST   /admin/categories(.:format)          admin/categories#create
#       new_admin_category GET    /admin/categories/new(.:format)      admin/categories#new
#      edit_admin_category GET    /admin/categories/:id/edit(.:format) admin/categories#edit
#           admin_category GET    /admin/categories/:id(.:format)      admin/categories#show
#                          PATCH  /admin/categories/:id(.:format)      admin/categories#update
#                          PUT    /admin/categories/:id(.:format)      admin/categories#update
#                          DELETE /admin/categories/:id(.:format)      admin/categories#destroy
#           admin_products GET    /admin/products(.:format)            admin/products#index
#                          POST   /admin/products(.:format)            admin/products#create
#        new_admin_product GET    /admin/products/new(.:format)        admin/products#new
#       edit_admin_product GET    /admin/products/:id/edit(.:format)   admin/products#edit
#            admin_product GET    /admin/products/:id(.:format)        admin/products#show
#                          PATCH  /admin/products/:id(.:format)        admin/products#update
#                          PUT    /admin/products/:id(.:format)        admin/products#update
#                          DELETE /admin/products/:id(.:format)        admin/products#destroy
# 

Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    unauthenticated do
      root 'home#unregistered', as: :unauthenticated_root
    end
  end

  namespace :customer do
    resources :home, only: [:index]
    resources :products, only: [:index, :show]
  end

  namespace :admin do
    resources :home, only: [:index]

    resources :customers
    resources :categories
    resources :products do
      member do
        # get :report
      end
      collection do
        # get :report
      end
    end
  end

  resources :products, only: [:index, :show]
end

app/models/customer.rb
# == Schema Information
#
# Table name: customers
#
#  id         :integer          not null, primary key
#  username   :string           not null
#  active     :boolean          default(TRUE), not null
#  url        :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Customer < ActiveRecord::Base
  has_one :user, as: :profile
end

app/controllers/admin/customers_controller.rb
class Admin
  class CustomersController < ApplicationController
    before_action :valid_admin, :authenticate_user!
    before_action :set_customer, only: [:show, :edit, :update, :destroy]

    # GET /customers
    # GET /customers.json
    def index
      @customers = Customer.all
    end

    # GET /customers/1
    # GET /customers/1.json
    def show; end

    # GET /customers/new
    def new
      @customer = Customer.new
    end

    # GET /customers/1/edit
    def edit; end

    # POST /customers
    # POST /customers.json
    def create
      @customer = Customer.new(customer_params)

      respond_to do |format|
        if @customer.save
          format.html { redirect_to [:admin, @customer], notice: 'Customer was successfully created.' }
          format.json { render :show, status: :created, location: [:admin, @customer] }
        else
          format.html { render :new }
          format.json { render json: @customer.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /customers/1
    # PATCH/PUT /customers/1.json
    def update
      respond_to do |format|
        if @customer.update(customer_params)
          format.html { redirect_to [:admin, @customer], notice: 'Customer was successfully updated.' }
          format.json { render :show, status: :ok, location: [:admin, @customer] }
        else
          format.html { render :edit }
          format.json { render json: @customer.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /customers/1
    # DELETE /customers/1.json
    def destroy
      @customer.destroy
      respond_to do |format|
        format.html { redirect_to admin_customers_url, notice: 'Customer was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(
        :username,
        :active,
        :url
      )
    end
  end
end

app/controllers/customer/home_controller.rb
class Customer
  class HomeController < ApplicationController
    before_action :valid_customer, :authenticate_user!

    def index; end
  end
end

app/controllers/customer/products_controller.rb
class Customer
  class ProductsController < ApplicationController
    before_action :valid_customer, :authenticate_user!
    before_action :set_product, only: [:show]

    # GET /products
    # GET /products.json
    def index
      @products = Product.all
    end

    # GET /products/1
    # GET /products/1.json
    def show; end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/admin/customers/_form.html.erb
<div class="container">
  <%= simple_form_for [:admin, @customer] do |f| %>
  <% if @customer.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

    <ul>
    <% @customer.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <%= f.input :username %>
  <%= f.label :active %>
  <%= f.collection_radio_buttons :active, [[true, 'Yes'] ,[false, 'No']], :first, :last %>
  <%= f.input :url %>

  <%= f.button :submit %>
<% end %>

</div>

app/views/admin/customers/edit.html.erb
<div class="container">
  <h1>Editing Customer</h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin, @customer] %> |
<%= link_to 'Back', admin_customers_path %>

</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

<h1>Listing Customers</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Active</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.username %></td>
        <td><%= customer.active %></td>
        <td><%= customer.url %></td>
        <td><%= link_to 'Show', [:admin, customer] %></td>
        <td><%= link_to 'Edit', edit_admin_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', [:admin, customer], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer', new_admin_customer_path %>

</div>

app/views/admin/customers/new.html.erb
<div class="container">
  <h1>New Customer</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_customers_path %>

</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @customer.username %>
</p>

<p>
  <strong>Active:</strong>
  <%= @customer.active %>
</p>

<p>
  <strong>Url:</strong>
  <%= @customer.url %>
</p>

<%= link_to 'Edit', edit_admin_customer_path(@customer) %> |
<%= link_to 'Back', admin_customers_path %>

</div>