config/routes.rb
# == Route Map
root 'welcome#index'
#
#                   Prefix Verb   URI Pattern                          Controller#Action
#         new_user_session GET    /users/sign_in(.:format)             devise/sessions#new
#             user_session POST   /users/sign_in(.:format)             devise/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)            devise/sessions#destroy
#            user_password POST   /users/password(.:format)            devise/passwords#create
#        new_user_password GET    /users/password/new(.:format)        devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format)       devise/passwords#edit
#                          PATCH  /users/password(.:format)            devise/passwords#update
#                          PUT    /users/password(.:format)            devise/passwords#update
# cancel_user_registration GET    /users/cancel(.:format)              devise/registrations#cancel
#        user_registration POST   /users(.:format)                     devise/registrations#create
#    new_user_registration GET    /users/sign_up(.:format)             devise/registrations#new
#   edit_user_registration GET    /users/edit(.:format)                devise/registrations#edit
#                          PATCH  /users(.:format)                     devise/registrations#update
#                          PUT    /users(.:format)                     devise/registrations#update
#                          DELETE /users(.:format)                     devise/registrations#destroy
#     unauthenticated_root GET    /                                    home#index
#      customer_home_index GET    /customer/home(.:format)             customer/home#index
#         admin_home_index GET    /admin/home(.:format)                admin/home#index
#          admin_customers GET    /admin/customers(.:format)           admin/customers#index
#                          POST   /admin/customers(.:format)           admin/customers#create
#       new_admin_customer GET    /admin/customers/new(.:format)       admin/customers#new
#      edit_admin_customer GET    /admin/customers/:id/edit(.:format)  admin/customers#edit
#           admin_customer GET    /admin/customers/:id(.:format)       admin/customers#show
#                          PATCH  /admin/customers/:id(.:format)       admin/customers#update
#                          PUT    /admin/customers/:id(.:format)       admin/customers#update
#                          DELETE /admin/customers/:id(.:format)       admin/customers#destroy
#         admin_categories GET    /admin/categories(.:format)          admin/categories#index
#                          POST   /admin/categories(.:format)          admin/categories#create
#       new_admin_category GET    /admin/categories/new(.:format)      admin/categories#new
#      edit_admin_category GET    /admin/categories/:id/edit(.:format) admin/categories#edit
#           admin_category GET    /admin/categories/:id(.:format)      admin/categories#show
#                          PATCH  /admin/categories/:id(.:format)      admin/categories#update
#                          PUT    /admin/categories/:id(.:format)      admin/categories#update
#                          DELETE /admin/categories/:id(.:format)      admin/categories#destroy
#           admin_products GET    /admin/products(.:format)            admin/products#index
#                          POST   /admin/products(.:format)            admin/products#create
#        new_admin_product GET    /admin/products/new(.:format)        admin/products#new
#       edit_admin_product GET    /admin/products/:id/edit(.:format)   admin/products#edit
#            admin_product GET    /admin/products/:id(.:format)        admin/products#show
#                          PATCH  /admin/products/:id(.:format)        admin/products#update
#                          PUT    /admin/products/:id(.:format)        admin/products#update
#                          DELETE /admin/products/:id(.:format)        admin/products#destroy
# 

Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    unauthenticated do
      root 'home#unregistered', as: :unauthenticated_root
    end
  end

  namespace :customer do
    resources :home, only: [:index]
    resources :products, only: [:index, :show]
  end

  namespace :admin do
    resources :home, only: [:index]

    resources :customers
    resources :categories
    resources :products do
      member do
        # get :report
      end
      collection do
        # get :report
      end
    end
  end

  resources :products, only: [:index, :show]
end

app/views/shared/_logout.html.erb
<% unless current_user.nil? %>
  <ul id="dropdown1" class="dropdown-content">
    <li>
      <a href="<%= destroy_user_session_path %>" data-method="delete">Sign out</a>
    </li>
  </ul>
  <ul id="dropdown2" class="dropdown-content">
    <li>
      <a href="<%= destroy_user_session_path %>" data-method="delete">Sign out</a>
    </li>
  </ul>
  <nav>
    <div class="nav-wrapper blue-grey darken-3 ">
      <a href="#" class="brand-logo center hide-on-med-and-down">
        <img src="/assets/img/logo-white.png" class="responsive-img icon"/> 
      </a>
      <ul id=" nav-mobile" class="left ">
        <% if current_user.customer? %>
          <li>
            <a href="<%= customer_home_index_path %>">
              <img src="/assets/img/HOME-BL.png" class="responsive-img icon"/>
            </a>
          </li>
          <li>
            <a href="<%= customer_products_path %>">
            <img src="/assets/img/teawhite.png" class="responsive-img icon"/>
            </a>
          </li>
          <% elsif current_user.admin? %>
            <li>
              <a href="<%= admin_home_index_path %>">
                <img src="/assets/img/HOME-BL.png" class="responsive-img icon"/>
              </a>
            </li>
            <li>
              <a href="<%= admin_categories_path %>">
                <img src="/assets/img/orders-white.png" class="responsive-img icon"/>
              </a>
            </li>
            <li>
              <a href="<%= admin_products_path %>">
                <img src="/assets/img/productos-wth.png" class="responsive-img icon"/>
              </a>
            </li>
            <% end%>
      </ul>
      <ul id="nav-mobile1" class="right hide-on-med-and-down">

        <li>
          <a class="dropdown-button" href="#!" data-activates="dropdown1">
            <%=current_user.email %>
              <i class="material-icons right">arrow_drop_down</i>
          </a>
        </li>
      </ul>
      <ul id="nav-mobile2" class="right hide-on-large-only">
        <li>
          <a class="dropdown-button" href="#!" data-activates="dropdown2">
              <i class="material-icons right">menu</i>
          </a>
        </li>
      </ul>
    </div>
  </nav>
<% end %>

app/views/shared/_messages.html.erb
<% unless notice.blank? %>
	<input id="notif-type" type="hidden" value="success" />
	<input id="notif-msg" type="hidden" value="<%= notice %>" />
	<input id="notif-duration" type="hidden" value="10" />
<% end %>
<% unless alert.blank? %>
	<input id="notif-type" type="hidden" value="alert" />
	<input id="notif-msg" type="hidden" value="<%= alert %>" />
	<input id="notif-duration" type="hidden" value="10" />
<% end %>

app/views/shared/_navbar.html.erb
  <ul id="dropdown2" class="dropdown-content">
    <li>
      <a href="<%= new_user_session_path %>">Sign in</a>
    </li>
  </ul>
  <nav>
    <div class="nav-wrapper blue-grey darken-3">
      <a href="#" class="brand-logo center">
        <img src="/assets/img/logo-white.png" class="responsive-img icon"/>       
      </a>

      <ul id=" nav-mobile" class="left">
        <a href="<%= unauthenticated_root_path %>">
          <img src="/assets/img/HOME-BL.png" class="responsive-img icon"/>
        </a>
      </ul>

      <ul id=" nav-mobile" class="left ">
          <a href="<%= products_path %>">
          <img src="/assets/img/teawhite.png" class="responsive-img icon"/>
        </a>
      </ul>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li>
          <a class="dropdown-button" href="#!" data-activates="dropdown1">
          </a>
        </li>
        <li>
          <a href="<%= new_user_session_path %>">Sign in</a>
        </li>
      </ul>
            <ul id="nav-mobile2" class="right hide-on-large-only">
        <li>
          <a class="dropdown-button" href="#!" data-activates="dropdown2">
              <i class="material-icons right">menu</i>
          </a>
        </li>
      </ul>
    </div>
  </nav>