config/routes.rb
# == Route Map
root 'welcome#index'
#
#                   Prefix Verb   URI Pattern                          Controller#Action
#         new_user_session GET    /users/sign_in(.:format)             devise/sessions#new
#             user_session POST   /users/sign_in(.:format)             devise/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)            devise/sessions#destroy
#            user_password POST   /users/password(.:format)            devise/passwords#create
#        new_user_password GET    /users/password/new(.:format)        devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format)       devise/passwords#edit
#                          PATCH  /users/password(.:format)            devise/passwords#update
#                          PUT    /users/password(.:format)            devise/passwords#update
# cancel_user_registration GET    /users/cancel(.:format)              devise/registrations#cancel
#        user_registration POST   /users(.:format)                     devise/registrations#create
#    new_user_registration GET    /users/sign_up(.:format)             devise/registrations#new
#   edit_user_registration GET    /users/edit(.:format)                devise/registrations#edit
#                          PATCH  /users(.:format)                     devise/registrations#update
#                          PUT    /users(.:format)                     devise/registrations#update
#                          DELETE /users(.:format)                     devise/registrations#destroy
#     unauthenticated_root GET    /                                    home#index
#      customer_home_index GET    /customer/home(.:format)             customer/home#index
#         admin_home_index GET    /admin/home(.:format)                admin/home#index
#          admin_customers GET    /admin/customers(.:format)           admin/customers#index
#                          POST   /admin/customers(.:format)           admin/customers#create
#       new_admin_customer GET    /admin/customers/new(.:format)       admin/customers#new
#      edit_admin_customer GET    /admin/customers/:id/edit(.:format)  admin/customers#edit
#           admin_customer GET    /admin/customers/:id(.:format)       admin/customers#show
#                          PATCH  /admin/customers/:id(.:format)       admin/customers#update
#                          PUT    /admin/customers/:id(.:format)       admin/customers#update
#                          DELETE /admin/customers/:id(.:format)       admin/customers#destroy
#         admin_categories GET    /admin/categories(.:format)          admin/categories#index
#                          POST   /admin/categories(.:format)          admin/categories#create
#       new_admin_category GET    /admin/categories/new(.:format)      admin/categories#new
#      edit_admin_category GET    /admin/categories/:id/edit(.:format) admin/categories#edit
#           admin_category GET    /admin/categories/:id(.:format)      admin/categories#show
#                          PATCH  /admin/categories/:id(.:format)      admin/categories#update
#                          PUT    /admin/categories/:id(.:format)      admin/categories#update
#                          DELETE /admin/categories/:id(.:format)      admin/categories#destroy
#           admin_products GET    /admin/products(.:format)            admin/products#index
#                          POST   /admin/products(.:format)            admin/products#create
#        new_admin_product GET    /admin/products/new(.:format)        admin/products#new
#       edit_admin_product GET    /admin/products/:id/edit(.:format)   admin/products#edit
#            admin_product GET    /admin/products/:id(.:format)        admin/products#show
#                          PATCH  /admin/products/:id(.:format)        admin/products#update
#                          PUT    /admin/products/:id(.:format)        admin/products#update
#                          DELETE /admin/products/:id(.:format)        admin/products#destroy
# 

Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    unauthenticated do
      root 'home#unregistered', as: :unauthenticated_root
    end
  end

  namespace :customer do
    resources :home, only: [:index]
    resources :products, only: [:index, :show]
  end

  namespace :admin do
    resources :home, only: [:index]

    resources :customers
    resources :categories
    resources :products do
      member do
        # get :report
      end
      collection do
        # get :report
      end
    end
  end

  resources :products, only: [:index, :show]
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id          :integer          not null, primary key
#  name        :string           not null
#  active      :boolean          default(TRUE), not null
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Category < ActiveRecord::Base
  has_many :products
end

app/controllers/admin/categories_controller.rb
class Admin
  class CategoriesController < ApplicationController
    before_action :valid_admin, :authenticate_user!
    before_action :set_category, only: [:show, :edit, :update, :destroy]

    # GET /categories
    # GET /categories.json
    def index
      @categories = Category.all
    end

    # GET /categories/1
    # GET /categories/1.json
    def show; end

    # GET /categories/new
    def new
      @category = Category.new
    end

    # GET /categories/1/edit
    def edit; end

    # POST /categories
    # POST /categories.json
    def create
      @category = Category.new(category_params)

      respond_to do |format|
        if @category.save
          format.html { redirect_to [:admin, @category], notice: 'Category was successfully created.' }
          format.json { render :show, status: :created, location: [:admin, @category] }
        else
          format.html { render :new }
          format.json { render json: @category.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /categories/1
    # PATCH/PUT /categories/1.json
    def update
      respond_to do |format|
        if @category.update(category_params)
          format.html { redirect_to [:admin, @category], notice: 'Category was successfully updated.' }
          format.json { render :show, status: :ok, location: [:admin, @category] }
        else
          format.html { render :edit }
          format.json { render json: @category.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /categories/1
    # DELETE /categories/1.json
    def destroy
      @category.destroy
      respond_to do |format|
        format.html { redirect_to admin_categories_url, notice: 'Category was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(
        :name,
        :active,
        :description
      )
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/_form.html.erb
<div class="container">
  <%= simple_form_for [:admin, @category] do |f| %>
  <% if @category.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

    <ul>
    <% @category.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <%= f.input :name %>
  <%= f.label :active %>
  <%= f.collection_radio_buttons :active, [[true, 'Yes'] ,[false, 'No']], :first, :last %>
  <%= f.input :description %>

  <%= f.button :submit %>
<% end %>

</div>

app/views/admin/categories/edit.html.erb
<div class="container">
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin, @category] %> |
<%= link_to 'Back', admin_categories_path %>

</div>

app/views/admin/categories/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

<h1>Listing Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Active</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.active %></td>
        <td><%= category.description %></td>
        <td><%= link_to 'Show', [:admin, category] %></td>
        <td><%= link_to 'Edit', edit_admin_category_path(category) %></td>
        <td><%= link_to 'Destroy', [:admin, category], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class="grey darken-4 btn">
  <%= link_to 'New Category', new_admin_category_path %>
</div>

</div>

app/views/admin/categories/new.html.erb
<div class="container">
  <h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_categories_path %>

</div>

app/views/admin/categories/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Active:</strong>
  <%= @category.active %>
</p>

<p>
  <strong>Description:</strong>
  <%= @category.description %>
</p>

<%= link_to 'Edit', edit_admin_category_path(@category) %> |
<%= link_to 'Back', admin_categories_path %>

</div>