config/routes.rb
# == Route Map
root 'welcome#index'
#
#                   Prefix Verb   URI Pattern                          Controller#Action
#         new_user_session GET    /users/sign_in(.:format)             devise/sessions#new
#             user_session POST   /users/sign_in(.:format)             devise/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)            devise/sessions#destroy
#            user_password POST   /users/password(.:format)            devise/passwords#create
#        new_user_password GET    /users/password/new(.:format)        devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format)       devise/passwords#edit
#                          PATCH  /users/password(.:format)            devise/passwords#update
#                          PUT    /users/password(.:format)            devise/passwords#update
# cancel_user_registration GET    /users/cancel(.:format)              devise/registrations#cancel
#        user_registration POST   /users(.:format)                     devise/registrations#create
#    new_user_registration GET    /users/sign_up(.:format)             devise/registrations#new
#   edit_user_registration GET    /users/edit(.:format)                devise/registrations#edit
#                          PATCH  /users(.:format)                     devise/registrations#update
#                          PUT    /users(.:format)                     devise/registrations#update
#                          DELETE /users(.:format)                     devise/registrations#destroy
#     unauthenticated_root GET    /                                    home#index
#      customer_home_index GET    /customer/home(.:format)             customer/home#index
#         admin_home_index GET    /admin/home(.:format)                admin/home#index
#          admin_customers GET    /admin/customers(.:format)           admin/customers#index
#                          POST   /admin/customers(.:format)           admin/customers#create
#       new_admin_customer GET    /admin/customers/new(.:format)       admin/customers#new
#      edit_admin_customer GET    /admin/customers/:id/edit(.:format)  admin/customers#edit
#           admin_customer GET    /admin/customers/:id(.:format)       admin/customers#show
#                          PATCH  /admin/customers/:id(.:format)       admin/customers#update
#                          PUT    /admin/customers/:id(.:format)       admin/customers#update
#                          DELETE /admin/customers/:id(.:format)       admin/customers#destroy
#         admin_categories GET    /admin/categories(.:format)          admin/categories#index
#                          POST   /admin/categories(.:format)          admin/categories#create
#       new_admin_category GET    /admin/categories/new(.:format)      admin/categories#new
#      edit_admin_category GET    /admin/categories/:id/edit(.:format) admin/categories#edit
#           admin_category GET    /admin/categories/:id(.:format)      admin/categories#show
#                          PATCH  /admin/categories/:id(.:format)      admin/categories#update
#                          PUT    /admin/categories/:id(.:format)      admin/categories#update
#                          DELETE /admin/categories/:id(.:format)      admin/categories#destroy
#           admin_products GET    /admin/products(.:format)            admin/products#index
#                          POST   /admin/products(.:format)            admin/products#create
#        new_admin_product GET    /admin/products/new(.:format)        admin/products#new
#       edit_admin_product GET    /admin/products/:id/edit(.:format)   admin/products#edit
#            admin_product GET    /admin/products/:id(.:format)        admin/products#show
#                          PATCH  /admin/products/:id(.:format)        admin/products#update
#                          PUT    /admin/products/:id(.:format)        admin/products#update
#                          DELETE /admin/products/:id(.:format)        admin/products#destroy
# 

Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    unauthenticated do
      root 'home#unregistered', as: :unauthenticated_root
    end
  end

  namespace :customer do
    resources :home, only: [:index]
    resources :products, only: [:index, :show]
  end

  namespace :admin do
    resources :home, only: [:index]

    resources :customers
    resources :categories
    resources :products do
      member do
        # get :report
      end
      collection do
        # get :report
      end
    end
  end

  resources :products, only: [:index, :show]
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id          :integer          not null, primary key
#  name        :string           not null
#  active      :boolean          default(TRUE), not null
#  url         :text
#  quantity    :integer          default(0), not null
#  amount      :decimal(, )      default(0.0), not null
#  category_id :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  price       :integer          default(0), not null
#  description :string(250)
#
# Indexes
#
#  index_products_on_category_id  (category_id)
#
# Foreign Keys
#
#  fk_rails_...  (category_id => categories.id)
#

#
# Indexes
#
#  index_products_on_category_id  (category_id)
#
# Foreign Keys
#
#  fk_rails_...  (category_id => categories.id)
#

class Product < ActiveRecord::Base
  belongs_to :category
end

app/controllers/admin/products_controller.rb
class Admin
  class ProductsController < ApplicationController
    before_action :valid_admin, :authenticate_user!
    before_action :set_product, only: [:show, :edit, :update, :destroy]

    # GET /products
    # GET /products.json
    def index
      @products = Product.all
    end

    # GET /products/1
    # GET /products/1.json
    def show; end

    # GET /products/new
    def new
      @product = Product.new
    end

    # GET /products/1/edit
    def edit; end

    # POST /products
    # POST /products.json
    def create
      @product = Product.new(product_params)

      respond_to do |format|
        if @product.save
          # binding.pry
          format.html { redirect_to [:admin, @product], notice: 'Product was successfully created.' }
          format.json { render :show, status: :created, location: [:admin, @product] }
        else
          format.html { render :new }
          format.json { render json: @product.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /products/1
    # PATCH/PUT /products/1.json
    def update
      respond_to do |format|
        if @product.update(product_params)
          format.html { redirect_to [:admin, @product], notice: 'Product was successfully updated.' }
          format.json { render :show, status: :ok, location: [:admin, @product] }
        else
          format.html { render :edit }
          format.json { render json: @product.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /products/1
    # DELETE /products/1.json
    def destroy
      @product.destroy
      respond_to do |format|
        format.html { redirect_to [:admin, @product], notice: 'Product was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(
        :name,
        :url,
        :quantity,
        :amount,
        :category_id
      )
    end
  end
end

app/controllers/customer/products_controller.rb
class Customer
  class ProductsController < ApplicationController
    before_action :valid_customer, :authenticate_user!
    before_action :set_product, only: [:show]

    # GET /products
    # GET /products.json
    def index
      @products = Product.all
    end

    # GET /products/1
    # GET /products/1.json
    def show; end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show; end

  protected

  def set_layout
    'landing'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.erb
<%= simple_form_for [:admin, @product] do |f| %>
  <% if @product.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

    <ul>
    <% @product.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <%= f.input :name %>
  <%= f.input :url %>
  <%= f.input :quantity %>
  <%= f.input :amount %>
  <%= f.association :category, include_blank: false %>
  <%= f.input :price %>
  <%= f.input :description %>

  <%= f.button :submit %>
<% end %>

app/views/admin/products/edit.html.erb
<div class="container">
  <h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_product_path(@product) %> |
<%= link_to 'Back', admin_products_path %>

</div>

app/views/admin/products/index.html.erb
<section>
  <p id="notice"><%= notice %></p>
  <div class="container">
    <div class="row">
      <div class="col s2 left-align">
        <%= image_tag("icons/user-gray.png", height: '80') %>
      </div>
      <div class="col s7 left-align">
        <h5>¡Bienvenido! <%= current_user.email %></h5>
      </div>
      <div class="col s3 right-align">
        <%= image_tag("logos/logo-color.png", height: '100') %>
      </div>
    </div>
  <p>Home > Productos</p1>

  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Url</th>
        <th>Quantity</th>
        <th>Amount</th>
        <th>Category</th>
        <th>Price</th>
        <th>Description</th>

        <th colspan="3"></th>
      </tr>
    </thead>
 
    <tbody>
      <% @products.each do |product| %>
        <tr>
          <td><%= product.name %></td>
          <td><img src="<%= product.url %>" alt="" class="logocolor"></td>
          <td><%= product.quantity %></td>
          <td><%= product.amount %></td>
          <td><%= product.category.id %></td>
          <td><%= product.price %></td>
          <td><%= product.description %></td>
          <td><%= link_to 'Show', admin_product_path(product) %></td>
          <td><%= link_to 'Edit', edit_admin_product_path(product) %></td>
          <td><%= link_to 'Destroy', admin_product_path(product), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to new_admin_product_path do %>
    <%= image_tag("icons/productos-drk.png", height: '30') %>
  <% end %>
  </div>
</section>

app/views/admin/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_products_path %>

app/views/admin/products/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<img src="<%= @product.url %>" class="responsive-img producto"/>


<p>
  <strong>Quantity:</strong>
  <%= @product.quantity %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @product.amount %>
</p>

<p>
  <strong>Category:</strong>
  <%= @product.category.id %>
</p>
<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>
<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>


<%= link_to 'Edit', edit_admin_product_path(@product) %> |
<%= link_to 'Back', admin_products_path %>

</div>